version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: temutukar_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - laravel
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=temutukar
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret

  db:
    image: postgis/postgis:latest
    container_name: postgres_postgis
    restart: always
    environment:
      POSTGRES_DB: temutukar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    networks:
      - laravel

  npm:
    image: node:20
    container_name: node_build
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: [ "sh", "-c", "npm install && npm run build" ]
    networks:
      - laravel

volumes:
  pgdata:
  geoserver_data:

networks:
  laravel:
    driver: bridge
