version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: temutukar
    container_name: temutukar
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
    expose:
      - 9000

  nginx:
    image: nginx:stable
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgis/postgis:17-3.4
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  geoserver:
    image: kartoza/geoserver:2.22.2
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
  geoserver_data:
