version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel

  node:
    build:
      context: ./docker/node
    container_name: node_build
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["tail", "-f", "/dev/null"]
    networks:
      - laravel

  db:
    image: postgis/postgis:14-3.3
    container_name: postgres_postgis
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
  geoserver_data:
